<?php
$people = array("Andrei", "Basile", "Bradley", "Carlos", "Chris", "Emilio", "Gordon", "Jennifer", "Johnny", "Joyce", "Judith", "Owen", "Oz", "Oscar", "Daniel", "Craig", "Vicente", "Yiyang");

$questions = array("Are you a morning person or a night owl?",
"Do you prefer mental or physical exercise?",
"How would you live your life if you found out you only had a year to live?",
"If were were extremely wealthy, what changes would you make in your life or the world?",
"If you could have any animal as a tame pet, which would you choose?",
"If you were able to live forever, would you want to do so? Why?",
"If you were given $100,000 to redecorate or remodel your house or apartment, what changes would you make?",
"Is it ever right to tell a lie? Explain your answer".
"What achievement are you most proud of?",
"What annoys you?",
"What book has had a significant impact on you?",
"What book or movie character are you most like?",
"What country or place in the world would you most/least like to visit?",
"What famous person either dead or alive would you most want to meet?",
"What food did you hate as a child but enjoy now?",
"Do your follow your horoscope?",
"What food or snack do you crave most?",
"What food would you be willing to eat for every meal for the rest of your life?",
"What historical event would you like to know the truth about?",
"Do you prefer to dress casually or in formal attire?",
"What is considered socially acceptable that you do not approve of?",
"What is something unusual you recommend everyone try at least once?",
"What item have you lost recently? Did you find it?",
"What is something you have recently learned that surprised you?",
"What is something you wish you could do better?",
"Where were you born and how many places have you lived?",
"What is strange or unusual about you?",
"What is the best advice anyone ever gave you? Who gave it to you?",
"What is your favorite flower/kind of candy?",
"What is the best and worst thing about being female?",
"Where is the last place you would ever want to visit?",
"Which one world problem would you choose to solve and why?",
"Who has had the biggest impact on your life?",
"Who or what are you most grateful for?",
"What is the most important lesson you have learned so far in life?",
"What is the strangest tradition your family has?",
"What is the worst and/or best date you have ever been on?",
"What is the worst movie you have ever seen or book you have ever read?",
"What is your favorite book, movie, and/or tv show?",
"What is your favorite childhood memory?",
"What is your favorite color? Why?",
"What kind of people annoy you?",
"What is your dream job?",
"Do you collect anything?",
"Do you consider yourself a country or city person?",
"Do you enjoy reality tv?",
"Do you prefer to travel by car, plane, boat, or train? Why?",
"How do you wake yourself up in the morning?",
"What do you do to relax?",
"What kind of music do you prefer?",
"What was the last vacation you took?",
"What, if anything, makes you afraid?",
"What, if anything, makes you angry?",
"Who or what makes you happy?",
"Would you enjoy a vacation away from all technology?",
"What one outfit or type of clothing would you choose to wear every day for the rest of your life?",
"What one subject can you talk about for hours?",
"What one thing you have done in your life has given you the most satisfaction?",
"What one trait do you have that makes you feel good about yourself?",
"What quote do you try to live by?",
"What trend that has died out would like to see come back?",
"What unusual item do you have in your purse right now?",
"What unusual or unpleasant smell do you really enjoy?",
"What word(s) do you always misspell?",
"What, if anything, do you consider yourself obsessed with?",
"Who is your oldest living relative?",
"What is the best and worst thing about being male?",
"Which movie do you like so much that you can you watch repeatedly?",
"What would you do/not do for a million dollars?",
"What is one thing you enjoyed when you were a child that you still enjoy?",
"What is the highest-pressure situation you have ever been in and how did you handle it?",
"What stresses you out?",
"What person or event made the biggest impact on your life?",
"If you could do one thing every day of your life for the rest of your life, what would it be?",
"What do you think you have done to make the world a better place?",
"Have you ever met anyone famous? Who?",
"What story from your life is the scariest/funniest/strangest?",
"If you could an expert in one area, what would it be?",
"What was the best/worst purchase you ever made?",
"Who is your favorite author/actor/actress? Why?",
"What characteristics makes a person \"successful?",
"What is the most unusual thing you have ever done?",
"What food do you absolutely hate? Why?",
"What do you think was the most horrible historic event? Why?",
"Who or what do you always make time for?",
"Have you ever walked out of a movie Why?",
"What was your favorite cartoon when you were a child?",
"What would others say you own too many of?",
"What is your perfect food/snack?",
"Who is your favorite fictional villain?",
"What game or sport do you enjoy, but are not very good at?",
"What is the weirdest thing you used to do when you were a child?",
"Have you ever cried at a movie? If so, which one(s)?",
"Which activity could you do all day and still enjoy?",
"What is something you think everyone should experience at least once in life?",
"Which country/state/city would like to move to?",
"What is your earliest/favorite childhood memory?",
"What is the most recent thing you learned?",
"What one thing personal item, excluding pets and family, would you most want to save if your house caught fire?",
"What was the best vacation you ever took?",
"What random act of kindness have you done recently?",
"What is the most useful skill you have?",
"What was the most historic event you either witnessed or took part in?",
"What compliment that someone gave you that really stuck in your memory?",
"What is your favorite/least favorite card/board game?",
"What about you do you think makes you unique?",
"If you could pick one talent to instantly be an expert at, which would you choose?",
"Is there anything you collect?",
"What common food ingredient, spice, or herb do you dislike the taste of?",
"What do you consider your best talent or ability?",
"What is your first thought when see a homeless person?",
"What was the worst injury you ever had and how did you get it?",
"What was your last major accomplished goal?",
"What is your creative outlet or interest?",
"What is something you have always wanted to do, but have not done yet?",
"What do you consider the best part of your day?",
"If you could run away from your current life and start over somewhere else, would you and where would you go?",
"Would you take a trip to a foreign country alone?",
"If you could have any animal as a tame pet, which would you choose?",
"What one personality trait do you wish everyone would have?",
"What is one thing you learned this week?",
"Would you want to live forever? Why or why not?",
"What is your favorite mode of transportation? Why?",
"What is the most extreme weather you have ever experienced?",
"Who is your favorite close relative?",
"Do you consider your childhood to have been good? Why or why not?",
"Would you consider yourself to be a \"fix it yourself\" or \"call an expert\" type of person?",
"Do you watch commercials on a recorded program or fast-forward through them?",
"What do you consider the most valuable possession you own?",
"Is there anything you regret doing or not doing?",
"What do you consider the most important thing you have done in your life?");

$questionIndex = array_rand($questions);
$personIndex = array_rand($people);
?>

<!doctype html>
<html>
    <head>
        <title>Random PT IceBreaker</title>
    </head>
    <body>
        <p><b><?= $people[$personIndex] ?>:</b> <?= $questions[$questionIndex] ?></p>
    </body>
</html>
